# Generated by Django 6.0 on 2026-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_component_is_on_offer_component_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='mpn',
            field=models.CharField(max_length=100, verbose_name='Manufacturer Part Number'),
        ),
    ]
